### ISSUE TITLE
Generate UML2.ecore failed

### ISSUE THREAD

**Issue by keven11111112** [crossecore/crossecore-generator#1]
I tried:
java -jar build/libs/crossecore-generator_20200208-0324.jar  -L typescript -e ./model/UML2.ecore -p ./output/

but get:
Exception in thread "main" java.lang.NullPointerException
        at com.crossecore.typescript.TypeScriptTypeTranslator2.import_(TypeScriptTypeTranslator2.java:54)
        at com.crossecore.typescript.TypeScriptTypeTranslator2.translateType(TypeScriptTypeTranslator2.java:264)
        at com.crossecore.typescript.TypeScriptTypeTranslator2.translateType(TypeScriptTypeTranslator2.java:347)
        at com.crossecore.typescript.ModelGenerator.caseEAttribute(ModelGenerator.java:568)
        at com.crossecore.typescript.ModelGenerator.caseEClass(ModelGenerator.java:168)
        at com.crossecore.typescript.ModelGenerator.caseEClass(ModelGenerator.java:47)
        at org.eclipse.emf.ecore.util.EcoreSwitch.doSwitch(EcoreSwitch.java:106)
        at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
        at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
        at com.crossecore.typescript.ModelGenerator.caseEPackage(ModelGenerator.java:87)
        at com.crossecore.typescript.ModelGenerator.caseEPackage(ModelGenerator.java:47)
        at org.eclipse.emf.ecore.util.EcoreSwitch.doSwitch(EcoreSwitch.java:188)
        at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
        at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
        at com.crossecore.typescript.ModelGenerator.write(ModelGenerator.java:63)
        at com.crossecore.CrossEcore.createTypeScript(CrossEcore.java:284)
        at com.crossecore.CrossEcore.main(CrossEcore.java:162)

UML2.ecore, UML2_.ecore and UML_mod.ecore both failed.

**Comment by schwichti** [comment]
There are two problems:

# frist problem
The original [UML.ecore](http://git.eclipse.org/c/uml2/org.eclipse.uml2.git/tree/plugins/org.eclipse.uml2.uml/model/UML.ecore) contains some crossreferencing URIs that cannot be resolved outside Eclipse. You can workaround it like so:
* Download UML.ecore, [Types.ecore](https://git.eclipse.org/c/uml2/org.eclipse.uml2.git/tree/plugins/org.eclipse.uml2.types/model/Types.ecore), and Ecore.ecore
* Open UML.ecore in a text editor and replace all occurences of the kind `eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"` by `eType="ecore:EDataType file:///path/to/your/local/copy/Ecore.ecore#//EDiagnosticChain"` and `eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"` by `eType="ecore:EDataType file:///path/to/your/local/copy/Types.ecore#//Boolean"`

I did this once for `models/UML2.ecore` but this won't work for you because your filesystem is different.

# second problem
The TypeScript generator has a feature that simulates method overloading. This currently has a class cast exception bug for UML2.ecore

**Comment by keven11111112** [comment]
thanks a lot.
